// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reactivities.Persistance;

#nullable disable

namespace Reactivities.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220814133143_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Reactivities.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("727fcebe-800f-4b0b-bffc-c53b215f3e9b"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 6, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3374),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("3f91340d-6214-4200-9312-21cd60654fd2"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 7, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3420),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("945fd28d-abdb-48cd-8c39-dc0192578bc8"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 9, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3425),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("b6974c66-23cb-4980-84ef-197f7eb9776f"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 10, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3428),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("440b8ad0-5b40-4805-a7b2-52d04d670beb"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 11, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3431),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("74c44b38-57a1-4f40-ae59-ae1d1597f64f"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 12, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3439),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("0a70036a-e2fe-4fcb-9fba-a6af8cb0dc54"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 1, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3442),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("7668de5d-2fed-421f-b553-7d69c5715998"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 2, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3446),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("9018b4b6-4347-4f33-a3ac-8fbc2b89f1ce"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 3, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3450),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("dd07fe2e-7e2e-4dd7-9fae-9faad6f96815"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2023, 4, 14, 16, 31, 43, 84, DateTimeKind.Local).AddTicks(3453),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
